typedef unsigned char   undefined;

typedef unsigned char    byte;
typedef unsigned char    undefined1;
typedef unsigned short    undefined2;
#define unkbyte9   unsigned long long
#define unkbyte10   unsigned long long
#define unkbyte11   unsigned long long
#define unkbyte12   unsigned long long
#define unkbyte13   unsigned long long
#define unkbyte14   unsigned long long
#define unkbyte15   unsigned long long
#define unkbyte16   unsigned long long

#define unkuint9   unsigned long long
#define unkuint10   unsigned long long
#define unkuint11   unsigned long long
#define unkuint12   unsigned long long
#define unkuint13   unsigned long long
#define unkuint14   unsigned long long
#define unkuint15   unsigned long long
#define unkuint16   unsigned long long

#define unkint9   long long
#define unkint10   long long
#define unkint11   long long
#define unkint12   long long
#define unkint13   long long
#define unkint14   long long
#define unkint15   long long
#define unkint16   long long

#define unkfloat1   float
#define unkfloat2   float
#define unkfloat3   float
#define unkfloat5   double
#define unkfloat6   double
#define unkfloat7   double
#define unkfloat9   long double
#define unkfloat11   long double
#define unkfloat12   long double
#define unkfloat13   long double
#define unkfloat14   long double
#define unkfloat15   long double
#define unkfloat16   long double

#define BADSPACEBASE   void
#define code   void




void entrypoint(char *param_1,undefined1 *param_2,byte param_3,byte param_4,byte param_5,byte param_6,byte param_7);
void i2c_write_bytes(byte param_1,byte param_2,byte param_3,undefined1 param_4);
void i2c_write_byte(byte param_1,byte param_2,byte param_3);
void acpi_ec_init(byte param_1,byte param_2);
void irq_null(void);
void irq_watchdog(void);
void irq_toggle(void);
void irq_ack(undefined1 param_1);
undefined FUN_CODE_00f5(undefined1 * param_1);
undefined1 irq_getchar(void);
void irq_print_char(undefined1 *param_1,undefined1 param_2,char param_3);
void FUN_CODE_012a(byte param_1);
void format_putchar(char param_1);
void format_putchar_ext(undefined1 *param_1,undefined1 param_2,char param_3,undefined1 param_4);
void printf_core(char *param_1,byte param_2,char param_3);
void format_number(byte param_1);
void format_number_base(byte param_1,char param_2);
void format_prefix(char param_1);
byte ps2_process_command(void);
void FUN_CODE_06ff(undefined1 *param_1);
void ps2_send_bytes(byte param_1,byte param_2,byte param_3,byte param_4);
void ps2_set_response_ready(void);
void ps2_error_handler(void);
void ps2_write_cw(void);
void ps2_write_cr(char param_1);
void ps2_write_cmd(char param_1);
void fan_control_task(byte param_1,byte param_2,byte param_3);
void fan_state_machine(void);
undefined1 timer_delay_5ms(undefined1 param_1);
undefined1 timer_delay_ms_short(byte param_1,undefined1 param_2);
undefined1 timer_delay_ms_med(byte param_1,undefined1 param_2);
void FUN_CODE_0e5f(void);
void acpi_ec_write_cmd(byte param_1,byte param_2,byte param_3,undefined1 param_4);
void fan_pwm_off(void);
undefined1 FUN_CODE_0ff4(undefined2 *param_1);
char FUN_CODE_1007(char param_1,char *param_2,undefined1 param_3,char param_4);
undefined1 FUN_CODE_102b(undefined2 param_1,byte param_2,char param_3,char param_4);
void mem_write_byte(undefined1 param_1,undefined1 *param_2,undefined1 param_3,char param_4);
void mem_write_byte_offset(undefined1 param_1,undefined2 param_2,byte param_3,char param_4,char param_5);
void mem_increment(char param_1,short param_2,byte param_3);
byte mem_or(byte param_1,byte param_2);
byte mem_borrow(char param_1,byte param_2,byte param_3,byte param_4,char param_5,char param_6,char param_7,char param_8);
byte mem_shift_right(byte param_1,byte param_2,byte param_3,byte param_4,byte param_5);
byte mem_shift_left(byte param_1,byte param_2,byte param_3,byte param_4,byte param_5);
undefined1 mem_read_word(short param_1);
undefined1 mem_read_byte_ptr(short param_1);
void mem_add_24bit(byte param_1,short param_2);
void mem_write_quad(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,undefined1 param_5);
void FUN_CODE_113f(undefined2 param_1);
undefined1 mem_write_ptr(undefined1 *param_1,undefined1 param_2,undefined1 param_3);
char mem_mul_add(byte param_1,undefined2 param_2,byte param_3);
undefined1 mem_read_offset(short param_1);
void mem_write_triplet(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4);
undefined1 mem_read_offset2(short param_1);
void dispatch_table(char param_1);
void jump_table_call(undefined1 param_1,undefined1 param_2);
undefined1 mem_read_byte_by_mode(undefined1 *param_1,undefined1 param_2,char param_3);
void mem_add_with_carry(char param_1,short param_2,byte param_3);
void ec_init_early(char *param_1,undefined1 *param_2,byte param_3,byte param_4,byte param_5,byte param_6,byte param_7);
void acpi_ec_set_register(undefined1 param_1,char param_2,char param_3);
void FUN_CODE_142b(undefined1 param_1,byte *param_2);
void acpi_ec_invalid_cmd(void);
char acpi_ec_cmd_handler(char param_1,byte param_2,byte param_3,byte param_4,byte param_5,byte param_6,byte param_7);
void thermal_print_error(byte param_1,byte param_2,byte param_3);
void fan_auto_mode(void);
undefined1 FUN_CODE_1819(undefined1 param_1,byte param_2,byte param_3,byte param_4);
void FUN_CODE_1853(byte param_1,char *param_2,byte param_3);
void acpi_ec_reset(undefined1 *param_1,byte param_2,byte param_3);
void fan_reset(void);
char FUN_CODE_1ace(undefined1 param_1,undefined1 param_2);
void pm_power_on(byte param_1);
void FUN_CODE_1c04(byte param_1);
undefined1 FUN_CODE_1c15(void);
undefined1 FUN_CODE_1c1d(short param_1);
void FUN_CODE_1c29(byte param_1);
undefined1 FUN_CODE_1c3a(undefined1 param_1);
void ps2_set_ack(void);
void ps2_send_data(byte param_1,byte param_2,byte param_3,byte param_4);
void ps2_read_buffer(char *param_1,byte param_2);
undefined1 ps2_set_data(undefined1 param_1);
void ps2_set_nack(void);
void ps2_process_response(void);
void acpi_ec_wait_ready(undefined1 *param_1);
void pm_set_power_state(byte param_1,byte param_2,byte param_3,byte param_4);
void fan_init_regs(void);
void fan_speed_monitor(byte param_1,byte param_2,byte param_3);
void ec_main_task(char param_1,byte param_2,byte param_3,byte param_4,byte param_5,byte param_6,byte param_7);
void print_newline(void);
void parse_and_exec(byte param_1,char param_2,char param_3);
char i2c_read_bytes(byte param_1,char param_2,char param_3,byte param_4,byte param_5);
void i2c_read_byte(byte param_1,byte param_2,char param_3,char param_4);
undefined1 i2c_write_register(undefined2 param_1,byte param_2,char param_3,char param_4,undefined1 param_5);
undefined1 i2c_get_status(void);
undefined1 spi_read_status(short param_1);
void spi_send_addr_data(byte param_1,undefined1 param_2,undefined1 param_3,char param_4);
void spi_prepare_cmd(undefined1 param_1,undefined1 *param_2,undefined1 param_3,char param_4,undefined1 param_5);
void spi_write_enable(byte param_1,byte param_2,byte param_3,byte param_4);
void spi_write_disable(byte param_1,byte param_2,byte param_3,byte param_4);
void spi_send_addr(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,undefined1 param_5);
void spi_wait_ready(short param_1);
void spi_set_cs(undefined1 param_1);
void spi_set_mode(undefined1 param_1,undefined1 *param_2);
char spi_calc_offset(void);
char spi_calc_offset_byte(byte param_1);
undefined1 spi_read_with_base(undefined1 param_1,undefined1 param_2,byte param_3);
undefined1 spi_read_byte_mul(byte param_1,short param_2,byte param_3);
undefined1 spi_read_next(short param_1);
char spi_calc_offset_mul(byte param_1,byte param_2);
void spi_read_mul_store(undefined2 param_1,byte param_2);
void spi_read_mul(byte param_1,undefined2 param_2);
undefined1 spi_get_flags(void);
undefined1 spi_read_short(short param_1);
void uart_print_hex_byte(byte param_1);
void pm_off_mode(void);
void acpi_ec_init_table(char param_1,undefined1 param_2);
void acpi_ec_main_init(char param_1,byte param_2,byte param_3);
void thermal_alert(byte param_1,byte param_2,byte param_3);
undefined1 adc_config(undefined1 param_1);
void adc_read(undefined1 param_1,undefined1 param_2);
void acpi_ec_poll(byte param_1,byte param_2,byte param_3);
undefined1 spi_flash_read_byte(void);
undefined1 FUN_CODE_25cb(undefined2 *param_1);
undefined1 spi_flash_read_at(byte param_1,short param_2);
void FUN_CODE_25d7(undefined1 param_1,undefined1 param_2);
void FUN_CODE_25ec(void);
void FUN_CODE_25ef(char param_1);
undefined1 spi_flash_read_status_byte(void);
undefined1 spi_flash_read_status_bit(undefined2 *param_1);
undefined1 spi_flash_read_at_status(byte param_1,short param_2);
byte FUN_CODE_2605(byte *param_1);
byte FUN_CODE_2606(byte param_1);
byte FUN_CODE_260d(void);
byte FUN_CODE_2610(byte *param_1);
void FUN_CODE_2617(undefined1 param_1);
void spi_flash_read(byte param_1,byte param_2,byte param_3,undefined1 param_4);
undefined1 spi_flash_write(byte param_1,byte param_2,byte param_3,undefined1 param_4);
undefined1 gpio_init_all(void);
char uart_putchar(char param_1);
void uart_putchar_noflow(undefined1 param_1);
void FUN_CODE_26f1(undefined1 param_1,undefined1 param_2);
void FUN_CODE_26f3(undefined1 param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_26fc(byte param_1,byte param_2,char param_3,char param_4);
void FUN_CODE_270f(void);
char FUN_CODE_2715(char param_1);
char FUN_CODE_2721(char param_1);
undefined1 acpi_ec_set_address(undefined1 param_1);
void pm_init_uart(void);
void pm_set_sleep(undefined1 param_1);
undefined1 FUN_CODE_27be(void);
undefined1 FUN_CODE_27c1(undefined2 *param_1);
undefined1 FUN_CODE_27c2(byte param_1,short param_2);
undefined1 FUN_CODE_27cd(void);
undefined1 FUN_CODE_27d0(undefined2 *param_1);
void init_command_table(char param_1);
undefined1 timer0_reload(undefined1 param_1);
void pm_wake_init(void);
void FUN_CODE_28ac(void);
void FUN_CODE_28b4(void);
byte FUN_CODE_28ba(void);
undefined1 acpi_ec_enable_event(undefined1 param_1);
undefined1 FUN_CODE_2977(undefined1 param_1);
char timer_delay_ms(char *param_1,undefined1 param_2,char param_3,byte param_4);
void FUN_CODE_29d6(void);
void FUN_CODE_29e6(void);
void FUN_CODE_29f6(void);
void FUN_CODE_2a06(void);
void FUN_CODE_2a16(void);
void FUN_CODE_2a26(void);
void FUN_CODE_2a36(void);
void init_cmd_78(char param_1);
void init_cmd_85(char param_1);
void init_spi_read(void);
void init_mem_table(undefined1 param_1,undefined1 param_2);
void null_subroutine(void);
void thunk_FUN_CODE_f1f3(char *param_1,undefined1 *param_2,char param_3,char param_4,byte param_5,byte param_6,byte param_7);
void FUN_CODE_4854(byte param_1,char param_2);
void FUN_CODE_494e(char param_1,char param_2,byte param_3,byte param_4,char param_5,char param_6);
void FUN_CODE_4962(void);
void FUN_CODE_4d4a(void);
undefined FUN_CODE_4f02(void);
void FUN_CODE_5015(char param_1,byte param_2,byte param_3,char param_4,char param_5,char param_6,char param_7);
void FUN_CODE_5056(byte param_1,char param_2,char param_3,char param_4,char param_5,char param_6,char param_7);
void FUN_CODE_5248(undefined1 param_1,undefined1 *param_2);
void FUN_CODE_52da(byte *param_1);
void FUN_CODE_566c(void);
void adc_setup_channel(byte *param_1,char param_2,undefined1 param_3,undefined1 param_4,byte param_5);
char FUN_CODE_5f25(undefined1 param_1,char param_2,char param_3,char param_4,char param_5);
undefined1 FUN_CODE_5f4b(undefined1 *param_1,undefined1 param_2,char param_3);
char FUN_CODE_5f64(char param_1,char *param_2,undefined1 param_3,char param_4);
undefined1 FUN_CODE_5f88(undefined2 param_1,byte param_2,char param_3,char param_4);
char FUN_CODE_5fb5(char param_1,char *param_2,undefined1 param_3,char param_4);
void FUN_CODE_5fd7(undefined1 param_1,undefined1 *param_2,undefined1 param_3,char param_4);
void FUN_CODE_5fe9(undefined1 param_1,undefined2 param_2,byte param_3,char param_4,char param_5);
char FUN_CODE_600b(char param_1,byte param_2,char param_3,byte param_4);
byte FUN_CODE_601d(char param_1,byte param_2,byte param_3,byte param_4);
void FUN_CODE_6072(char param_1,short param_2,byte param_3);
char FUN_CODE_6088(char param_1,short param_2,byte param_3);
undefined1 FUN_CODE_609e(undefined2 param_1,byte param_2,char param_3,char param_4);
char FUN_CODE_60d6(char param_1,char param_2,char param_3,byte param_4,char param_5,byte param_6,byte param_7,byte param_8);
char FUN_CODE_60e3(char param_1,byte param_2,byte param_3,byte param_4,char param_5,byte param_6,byte param_7,byte param_8);
byte FUN_CODE_616e(char param_1,char param_2,char param_3,byte param_4,byte param_5,byte param_6,byte param_7,byte param_8);
byte FUN_CODE_6200(byte param_1,byte param_2);
byte FUN_CODE_6223(char param_1,byte param_2,byte param_3,byte param_4,char param_5,char param_6,char param_7,char param_8);
byte FUN_CODE_6234(byte param_1,byte param_2,byte param_3,byte param_4,byte param_5);
byte FUN_CODE_6247(byte param_1,byte param_2,byte param_3,byte param_4,byte param_5);
undefined1 FUN_CODE_625a(short param_1);
undefined1 FUN_CODE_6266(short param_1);
void FUN_CODE_6274(byte param_1,short param_2);
void FUN_CODE_62a7(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,undefined1 param_5);
void FUN_CODE_62b3(undefined2 param_1);
undefined1 FUN_CODE_62ca(undefined1 *param_1,undefined1 param_2,undefined1 param_3);
char FUN_CODE_62e4(byte param_1,undefined2 param_2,byte param_3);
undefined1 FUN_CODE_62f0(short param_1);
void FUN_CODE_62f9(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4);
undefined1 FUN_CODE_6302(short param_1);
void FUN_CODE_630e(char param_1);
void FUN_CODE_6334(undefined1 param_1,undefined1 param_2);
void FUN_CODE_6338(undefined *UNRECOVERED_JUMPTABLE);
byte FUN_CODE_633a(undefined1 *param_1,undefined1 param_2,byte param_3,byte param_4);
char FUN_CODE_7288(undefined1 *param_1,undefined1 param_2);
void FUN_CODE_74d8(undefined1 *param_1,undefined1 *param_2,char param_3);
void led_set_brightness(byte param_1);
byte FUN_CODE_796f(char param_1,char param_2,undefined1 param_3,byte param_4,byte param_5,byte param_6,char param_7);
void FUN_CODE_7ba4(char param_1,char param_2,undefined1 param_3,byte param_4,byte param_5,byte param_6,byte param_7,char param_8);
void FUN_CODE_7dd8(undefined1 param_1,char param_2,byte param_3);
void FUN_CODE_8026(void);
void FUN_CODE_8046(void);
void FUN_CODE_804a(void);
void FUN_CODE_804e(void);
void FUN_CODE_8051(void);
void FUN_CODE_8056(void);
void FUN_CODE_805e(void);
void FUN_CODE_8066(void);
void FUN_CODE_806a(void);
void FUN_CODE_8086(void);
void FUN_CODE_808e(void);
void FUN_CODE_8096(void);
void FUN_CODE_80a6(void);
void FUN_CODE_80ae(void);
void FUN_CODE_80b6(void);
void FUN_CODE_80be(void);
void FUN_CODE_80ce(void);
char thunk_FUN_CODE_dbac(void);
void FUN_CODE_80fe(char param_1,undefined1 param_2,char param_3,byte param_4);
void FUN_CODE_82ec(undefined1 param_1,undefined1 *param_2);
void fan_update_speed(void);
void FUN_CODE_84fb(undefined1 *param_1,char param_2);
void FUN_CODE_86e5(undefined1 *param_1,char param_2,char param_3,undefined1 param_4,char param_5,char param_6);
void FUN_CODE_8800(undefined1 *param_1,byte param_2,char param_3,char param_4);
void FUN_CODE_88c5(void);
void gpio_save_state(char param_1);
void gpio_restore_state(undefined1 param_1,undefined1 *param_2);
byte FUN_CODE_8aa7(undefined1 *param_1,char param_2);
void FUN_CODE_8c58(undefined1 *param_1,char param_2);
void FUN_CODE_8c64(undefined1 *param_1,char param_2,char param_3);
void fan_set_speed(void);
void gpio_restore_context(void);
undefined1 FUN_CODE_9003(undefined1 *param_1,undefined1 *param_2);
void FUN_CODE_919a(void);
void FUN_CODE_91bb(void);
void FUN_CODE_91e0(void);
void FUN_CODE_9203(void);
void FUN_CODE_9208(void);
void FUN_CODE_920d(void);
void FUN_CODE_9212(void);
void FUN_CODE_9221(void);
void FUN_CODE_9226(void);
void FUN_CODE_922b(void);
void FUN_CODE_9230(void);
void FUN_CODE_9235(void);
void FUN_CODE_923a(void);
void FUN_CODE_923f(void);
void FUN_CODE_9244(void);
void FUN_CODE_9249(void);
void FUN_CODE_924e(void);
void FUN_CODE_9253(void);
void FUN_CODE_9258(void);
void FUN_CODE_925d(void);
void FUN_CODE_9262(void);
void FUN_CODE_9267(void);
void FUN_CODE_9271(void);
void FUN_CODE_9276(void);
void FUN_CODE_927b(void);
void FUN_CODE_9280(void);
void FUN_CODE_9285(void);
void FUN_CODE_928a(void);
void FUN_CODE_928f(void);
void FUN_CODE_9294(void);
void FUN_CODE_9299(void);
void FUN_CODE_929e(void);
void FUN_CODE_92a3(void);
void FUN_CODE_92a8(void);
void FUN_CODE_92ad(void);
void FUN_CODE_92b2(void);
void FUN_CODE_92b7(void);
void FUN_CODE_92bc(void);
void FUN_CODE_92c1(void);
void FUN_CODE_92c6(void);
void FUN_CODE_92cb(void);
void FUN_CODE_92d0(void);
void FUN_CODE_92d5(void);
void FUN_CODE_92da(void);
void thermal_init(char *param_1,char param_2,byte param_3,byte param_4,byte param_5);
void FUN_CODE_9494(void);
void FUN_CODE_9617(char param_1,undefined1 *param_2,char param_3,char param_4,byte param_5);
undefined FUN_CODE_9714(byte param_1);
void FUN_CODE_9736(char param_1,byte param_2);
void FUN_CODE_9752(char param_1);
undefined1 FUN_CODE_9904(void);
undefined1 FUN_CODE_9907(short param_1);
undefined1 FUN_CODE_9912(void);
undefined1 FUN_CODE_9915(undefined1 *param_1);
char FUN_CODE_9920(short param_1,char param_2,char param_3,byte param_4,char param_5,byte param_6,char param_7,byte param_8);
char FUN_CODE_9926(char param_1,char param_2,char param_3,byte param_4);
void FUN_CODE_992e(byte param_1,byte param_2,char param_3,byte param_4);
void FUN_CODE_993b(byte param_1,byte param_2,byte param_3,byte param_4);
char FUN_CODE_9943(byte param_1,byte param_2,byte param_3,byte param_4);
char FUN_CODE_994c(byte *param_1);
void FUN_CODE_9960(byte param_1,byte param_2,byte param_3,byte param_4);
void FUN_CODE_9966(undefined1 param_1,undefined1 *param_2,char param_3,byte param_4,undefined1 param_5);
void FUN_CODE_9971(void);
undefined1 FUN_CODE_997d(void);
undefined1 FUN_CODE_9986(char param_1,byte param_2);
undefined1 FUN_CODE_998d(byte param_1,char param_2,byte param_3);
void FUN_CODE_9997(undefined1 param_1);
void FUN_CODE_999d(undefined1 param_1);
void FUN_CODE_99a5(char param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_99ab(undefined1 *param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4);
void FUN_CODE_99b4(undefined1 *param_1);
char FUN_CODE_99bd(char *param_1);
undefined1 FUN_CODE_99c3(undefined1 param_1);
void FUN_CODE_99cc(byte param_1,byte param_2,char param_3,byte param_4);
char FUN_CODE_99de(byte param_1);
char FUN_CODE_99e3(void);
undefined1 FUN_CODE_99eb(void);
void FUN_CODE_99f3(void);
void FUN_CODE_99f8(void);
char FUN_CODE_99ff(void);
char FUN_CODE_9a02(char *param_1);
void FUN_CODE_9a0a(void);
void FUN_CODE_9a11(undefined1 param_1);
char FUN_CODE_9a1e(void);
char FUN_CODE_9a26(void);
char FUN_CODE_9a2e(void);
void FUN_CODE_9a36(undefined1 param_1,undefined1 *param_2,char param_3,undefined1 param_4,undefined1 param_5);
undefined1 FUN_CODE_9a3d(void);
undefined1 FUN_CODE_9a48(void);
undefined1 FUN_CODE_9a52(undefined1 param_1,undefined1 param_2,undefined1 param_3);
char FUN_CODE_9a66(char param_1);
char FUN_CODE_9a6d(char param_1);
void FUN_CODE_9a74(void);
undefined FUN_CODE_9b0e(undefined1 * param_1);
byte FUN_CODE_9bcb(byte param_1);
undefined1 FUN_CODE_9cb3(byte param_1, undefined2 param_2);
void FUN_CODE_9d20(char param_1,undefined1 param_2);
undefined1 FUN_CODE_9e6b(undefined1 param_1);
byte FUN_CODE_a39c(void);
void FUN_CODE_a4c1(char param_1,undefined1 *param_2,char param_3,char param_4,char param_5,byte param_6,char param_7);
void gpio_restore_all(void);
void FUN_CODE_a824(char param_1,undefined1 param_2,char param_3,char param_4,undefined1 param_5,byte param_6);
void FUN_CODE_a8ef(void);
void FUN_CODE_a8ff(char param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_a937(char param_1,undefined1 param_2,undefined1 param_3,undefined1 param_4,byte param_5);
undefined1 FUN_CODE_ac52(byte param_1);
undefined1 FUN_CODE_acaa(byte param_1,undefined1 *param_2);
void FUN_CODE_ad55(void);
void FUN_CODE_ae53(char param_1,char param_2,byte param_3,byte param_4,byte param_5,undefined1 param_6);
void FUN_CODE_af45(byte param_1);
byte FUN_CODE_b041(char param_1,byte param_2,byte param_3,byte param_4);
byte FUN_CODE_b2f8(char param_1);
void FUN_CODE_b3cf(char param_1,undefined1 param_2,char param_3,char param_4,char param_5,undefined1 param_6);
undefined1 FUN_CODE_b54a(short param_1);
undefined1 FUN_CODE_b555(byte param_1);
void FUN_CODE_b71f(undefined1 *param_1);
byte FUN_CODE_b7f0(char param_1,undefined1 *param_2,byte param_3,byte param_4);
void FUN_CODE_b8c1(void);
void FUN_CODE_ba5f(void);
void FUN_CODE_bb2c(void);
void FUN_CODE_bcbd(undefined1 *param_1,undefined1 param_2);
void FUN_CODE_bd80(void);
void FUN_CODE_c067(undefined1 param_1);
undefined1 FUN_CODE_c11e(undefined1 *param_1,char param_2,char param_3,undefined1 param_4);
undefined1 FUN_CODE_c3d9(void);
undefined1 FUN_CODE_c3ea(void);
undefined1 FUN_CODE_c3ed(undefined2 *param_1);
undefined1 FUN_CODE_c3ee(byte param_1,short param_2);
undefined1 FUN_CODE_c3f9(byte param_1);
undefined1 FUN_CODE_c3fc(byte param_1);
undefined1 FUN_CODE_c400(byte param_1,undefined2 param_2,byte param_3);
byte FUN_CODE_c416(void);
byte FUN_CODE_c41f(void);
byte FUN_CODE_c422(byte *param_1);
byte FUN_CODE_c423(byte param_1);
void FUN_CODE_c42a(void);
undefined1 FUN_CODE_c442(void);
undefined1 FUN_CODE_c448(undefined1 param_1);
void FUN_CODE_c451(short param_1);
void FUN_CODE_c458(void);
void FUN_CODE_c464(byte param_1,byte *param_2);
void FUN_CODE_c465(byte param_1,byte *param_2);
byte FUN_CODE_c46c(byte *param_1);
byte FUN_CODE_c473(byte *param_1);
void FUN_CODE_c47a(byte param_1,byte *param_2);
void FUN_CODE_c5d5(void);
void FUN_CODE_c67b(byte param_1,byte param_2);
void FUN_CODE_c721(byte *param_1,byte param_2);
byte FUN_CODE_c7c1(void);
void FUN_CODE_c8fb(undefined1 param_1,undefined1 param_2,undefined1 param_3);
char FUN_CODE_c996(char param_1,byte param_2);
void FUN_CODE_ca30(void);
void FUN_CODE_cb5e(char param_1,undefined1 param_2,char param_3,byte param_4,byte param_5);
byte FUN_CODE_cbf2(void);
void FUN_CODE_cc79(undefined1 param_1,undefined1 *param_2);
void FUN_CODE_cd19(undefined1 param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_cec7(void);
void FUN_CODE_cfd9(void);
undefined1 FUN_CODE_d052(void);
void FUN_CODE_d05e(void);
void FUN_CODE_d080(byte *param_1,char param_2);
void FUN_CODE_d165(undefined1 param_1,undefined1 param_2,undefined1 param_3,char param_4);
void FUN_CODE_d2ea(void);
byte FUN_CODE_d451(undefined1 *param_1,undefined1 param_2);
void FUN_CODE_d537(byte param_1,undefined1 param_2);
void FUN_CODE_d5a1(byte param_1,char param_2,char param_3);
void FUN_CODE_d605(byte param_1,byte *param_2,byte param_3,char param_4,char param_5);
void FUN_CODE_d618(undefined1 param_1,undefined1 *param_2,char param_3);
void FUN_CODE_d63c(byte param_1);
void FUN_CODE_d6dd(byte param_1,byte param_2,byte param_3,undefined1 param_4);
undefined1 FUN_CODE_d7a8(void);
undefined1 FUN_CODE_d800(undefined1 param_1,undefined1 *param_2,byte param_3);
void FUN_CODE_d8c0(byte param_1,byte param_2,char param_3,char param_4);
undefined1 FUN_CODE_d929(undefined1 param_1,undefined1 param_2,undefined1 param_3);
undefined1 FUN_CODE_d987(void);
undefined1 FUN_CODE_d989(void);
void FUN_CODE_d990(undefined1 *param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_d992(undefined1 *param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_d99a(undefined1 *param_1,undefined1 param_2);
byte FUN_CODE_d9a2(void);
byte FUN_CODE_d9ad(void);
byte FUN_CODE_d9b8(void);
byte FUN_CODE_d9c3(void);
byte FUN_CODE_d9ce(void);
byte FUN_CODE_d9d9(void);
char FUN_CODE_d9e4(byte param_1,char param_2,char param_3,char param_4,byte param_5);
void FUN_CODE_da41(byte param_1,byte param_2,byte param_3,undefined1 param_4);
void FUN_CODE_da9d(void);
undefined1 FUN_CODE_db53(byte param_1,byte param_2,byte param_3,undefined1 param_4);
char FUN_CODE_dbac(void);
void FUN_CODE_dbf9(void);
void FUN_CODE_dd0a(void);
void FUN_CODE_dd5d(void);
void FUN_CODE_ddaf(void);
void FUN_CODE_ddc0(undefined1 param_1,undefined1 *param_2);
void FUN_CODE_ddc5(short param_1,undefined1 param_2,undefined1 param_3);
undefined1 FUN_CODE_ddcb(byte *param_1);
void FUN_CODE_ddd7(byte *param_1);
void FUN_CODE_dddb(void);
byte FUN_CODE_dde3(void);
byte FUN_CODE_dde8(byte param_1);
byte FUN_CODE_ddef(void);
void FUN_CODE_ddf6(undefined1 param_1);
char FUN_CODE_de00(void);
void FUN_CODE_de50(void);
void FUN_CODE_dea0(undefined1 param_1);
void FUN_CODE_df3d(char param_1,undefined1 param_2,char param_3,byte param_4);
void FUN_CODE_dfd7(void);
char FUN_CODE_e07c(undefined1 param_1, short param_2);
undefined1 FUN_CODE_e0bb(void);
undefined1 FUN_CODE_e0c8(void);
void FUN_CODE_e0d5(byte param_1);
void FUN_CODE_e0e1(undefined1 param_1);
undefined1 FUN_CODE_e0ed(void);
undefined1 FUN_CODE_e0f8(undefined1 *param_1);
void FUN_CODE_e0ff(void);
char FUN_CODE_e106(void);
char FUN_CODE_e10a(byte param_1);
undefined1 FUN_CODE_e119(undefined1 param_1,undefined1 param_2,byte param_3);
undefined1 FUN_CODE_e11f(byte param_1,short param_2,byte param_3);
undefined1 FUN_CODE_e122(short param_1);
char FUN_CODE_e129(byte param_1,byte param_2);
void FUN_CODE_e135(byte param_1);
void FUN_CODE_e136(byte param_1,undefined2 param_2);
undefined1 FUN_CODE_e13c(void);
undefined1 FUN_CODE_e147(short param_1);
void uart_print_hex_byte_comma(byte param_1);
char FUN_CODE_e22b(byte param_1,byte param_2,byte param_3);
void FUN_CODE_e2bb(void);
byte FUN_CODE_e3d0(char param_1,char param_2,char param_3,byte param_4,byte param_5,byte param_6,byte param_7,byte param_8);
char FUN_CODE_e406(char param_1,char param_2,char param_3,char param_4);
void FUN_CODE_e414(void);
void FUN_CODE_e456(undefined1 param_1);
void FUN_CODE_e59c(char param_1,char param_2);
undefined1 FUN_CODE_e5f6(undefined1 param_1);
undefined1 FUN_CODE_e600(undefined1 param_1);
undefined1 FUN_CODE_e610(undefined1 param_1);
undefined1 FUN_CODE_e620(undefined1 param_1);
undefined1 FUN_CODE_e630(undefined1 param_1);
byte FUN_CODE_e63f(void);
undefined1 FUN_CODE_e67d(void);
undefined1 FUN_CODE_e680(undefined2 *param_1);
undefined1 FUN_CODE_e68c(void);
undefined1 FUN_CODE_e68f(undefined2 *param_1);
undefined1 FUN_CODE_e69b(byte param_1,byte *param_2);
char FUN_CODE_e6a8(char param_1,char param_2);
byte FUN_CODE_e6b3(void);
void FUN_CODE_e6f6(char param_1,byte param_2);
void FUN_CODE_e7dc(void);
byte FUN_CODE_e880(void);
void FUN_CODE_e8b6(char param_1);
void FUN_CODE_e8ea(char param_1);
void FUN_CODE_e91c(void);
void FUN_CODE_e94e(char *param_1,undefined1 *param_2,char param_3,char param_4,byte param_5,byte param_6,byte param_7);
undefined1 pm_gpio_init(void);
void FUN_CODE_e9e0(byte param_1,char param_2,byte param_3,char param_4);
void FUN_CODE_ea6f(undefined1 param_1,undefined1 param_2);
void FUN_CODE_ea71(undefined1 param_1,undefined1 param_2,undefined1 param_3);
void FUN_CODE_ea7a(byte param_1,byte param_2,char param_3,char param_4);
byte FUN_CODE_ea8d(short param_1,byte param_2,byte param_3,byte param_4,byte param_5);
void FUN_CODE_ea97(void);
void pm_uart_config(void);
undefined1 FUN_CODE_eaca(byte param_1);
void FUN_CODE_eb24(void);
char uart_putchar_flowctrl(char param_1);
void uart_putchar_flowctrl_cr(undefined1 param_1);
byte FUN_CODE_ebef(byte param_1);
void pm_sleep_mode(undefined1 param_1);
void FUN_CODE_ec33(void);
void FUN_CODE_ec54(void);
byte FUN_CODE_ed10(char *param_1,undefined1 param_2,char param_3,byte param_4);
void FUN_CODE_ed2d(void);
char FUN_CODE_ed7c(char *param_1,undefined1 param_2,char param_3,byte param_4);
void FUN_CODE_ed96(void);
void FUN_CODE_edaf(void);
char FUN_CODE_efc9(void);
void FUN_CODE_efdd(char param_1);
void FUN_CODE_f0ae(void);
void FUN_CODE_f0be(void);
void FUN_CODE_f0ce(void);
void FUN_CODE_f0de(void);
void FUN_CODE_f0ee(void);
void FUN_CODE_f0fe(void);
void FUN_CODE_f10e(void);
void FUN_CODE_f11e(void);
void FUN_CODE_f12e(void);
void FUN_CODE_f13e(void);
void FUN_CODE_f14e(void);
void FUN_CODE_f15e(undefined1 param_1);
void FUN_CODE_f16e(undefined1 param_1);
undefined1 FUN_CODE_f17e(void);
void FUN_CODE_f1c9(char param_1);
void FUN_CODE_f1d7(char param_1);
void FUN_CODE_f1e5(undefined1 param_1);
void FUN_CODE_f1f3(char *param_1,undefined1 *param_2,char param_3,char param_4,byte param_5,byte param_6,byte param_7);
byte FUN_CODE_f2ed(void);
void FUN_CODE_f2f5(void);
void FUN_CODE_f2fd(void);
void FUN_CODE_f305(void);
void FUN_CODE_f30d(void);
void FUN_CODE_f322(void);
void FUN_CODE_f330(void);
void FUN_CODE_f336(void);
void FUN_CODE_f33c(undefined1 param_1);
void thunk_FUN_CODE_923a(void);

